services:
  exporter:
    build:
      dockerfile: ./Dockerfile
    container_name: monitoring_ansible_exporter
    networks:
      - monitoring_network
    expose:
      - 8000

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    networks:
      - monitoring_network
    volumes:
      - prometheus_data:/prometheus
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    networks:
      - monitoring_network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
