services:
  exporter:
    image: ghcr.io/schneider-marco/open-monitor:latest
    container_name: monitoring_ansible_exporter
    networks:
      - monitoring_network
    volumes:
      - ./data/monitoring_ansible_exporter/ansible:/app/ansible
      - ./data/monitoring_ansible_exporter/config:/app/config

    expose:
      - 8000

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    networks:
      - monitoring_network
    volumes:
      - prometheus_data:/prometheus
      - ./data/monitoring_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    networks:
      - monitoring_network
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
